services:
  web-frontend:
    build: .
    container_name: nortia-web-frontend
    ports:
      - "5173:5173"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
